- name: install utility programs
  yum: name={{ item }} state=present disable_gpg_check=yes
  vars:
    item:
      - python
      - python-devel
      - python36
      - python-crypto
      - python-pip

- name: install python packages
  pip:
    name:
      - cryptography==3.3.2

- name: install python3 packages
  command: pip3 install cryptography==3.3.2

- name: Create /etc/pwx
  file: path=/etc/pwx state=directory

- name: copy cert key
  copy: src=insecure_ca.key owner=root group=root dest=/etc/ssl/insecure_ca.key

- name: copy ca
  copy: src=insecure_ca.crt owner=root group=root dest=/etc/pwx/insecure_ca.crt

- name: create server key
  command: openssl genrsa -out /etc/pwx/server.key 2048
  args:
    creates: /etc/pwx/server.key

- name: create server csr
  openssl_csr:
    path: /etc/pwx/server.csr
    privatekey_path: /etc/pwx/server.key
    subject_alt_name: "DNS:localhost,DNS:{{ inventory_hostname }},DNS:{{ ansible_eth0.ipv4.address }},DNS:{{ ansible_eth1.ipv4.address }}"

- name: create certs
  openssl_certificate:
    path: /etc/pwx/server.crt
    csr_path: /etc/pwx/server.csr
    ownca_path: /etc/pwx/insecure_ca.crt
    ownca_privatekey_path: /etc/ssl/insecure_ca.key
    provider: ownca
