- name: install v1.14 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.14.8-0
      - kubeadm-1.14.8-0
      - kubectl-1.14.8-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.14
    use_dockerce: true
