- name: install v1.15 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.15.5-0
      - kubeadm-1.15.5-0
      - kubectl-1.15.5-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.15
    use_dockerce: true
