- name: install v1.16 kubernetes
  yum: name={{ packages }} state=present disable_gpg_check=yes
  vars:
    packages:
      - kubelet-1.16.11-0
      - kubeadm-1.16.11-0
      - kubectl-1.16.11-0

- name: setting vars
  set_fact:
    kubeadm_kubernetes_version: stable-1.16
    use_dockerce: true
